apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-pvc
  namespace: scm
  annotations:
    volume.beta.kubernetes.io/storage-class: "dg-nfs-storage"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
